services:
  postgres:
    image: postgres:16-alpine
    container_name: matrix-postgres
    environment:
      POSTGRES_DB: matrix_db
      POSTGRES_USER: matrix
      POSTGRES_PASSWORD: matrix
    ports:
      - "5432:5432"
    volumes:
      - matrix-pgdata:/var/lib/postgresql/data

  mock-environnement:
    image: wiremock/wiremock:3.6.0
    container_name: matrix-mock-environnement
    command: [ "--global-response-templating" ]
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings

  kafka:
    image: apache/kafka:3.8.0
    container_name: matrix-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: matrix-kafka-ui
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8090:8080"

volumes:
  matrix-pgdata:
